"""Software Company Builder: analyze -> plan-as-PR -> status -> smoke test.

Honest boundaries: repository analysis and deployment STATUS are real when
credentials exist; autonomous production code changes and production
deploys always require approval; full autonomous coding is NOT claimed.
"""
from __future__ import annotations

from typing import Any


def analyze_repo(repo: str) -> dict[str, Any]:
    from app.devops.providers import github_repo_info

    out = github_repo_info(repo)
    if not out.get("ok"):
        return out
    d = out.get("data", {})
    return {"ok": True, "status": "OK",
            "analysis": {
                "repo": d.get("full_name"), "default_branch": d.get("default_branch"),
                "open_issues": d.get("open_issues"),
                "recommendation": ("Standard web stack assumed. Confirm framework "
                                   "before implementation planning.")}}


def plan_as_pr(repo: str, *, title: str, plan_markdown: str,
               head: str = "", base: str = "main") -> dict[str, Any]:
    """Open a PR containing ONLY the implementation plan document.

    Real code changes ride the normal GitHub review flow afterwards.
    Returns NOT_CONFIGURED without a token; never fakes a merge.
    """
    from app.devops.providers import github_open_pr

    if not head:
        return {"ok": False, "status": "FAILED",
                "error": "head branch required (never push straight to main)"}
    safe_title = (title or "MAICOS implementation plan")[:200]
    return github_open_pr(repo, f"[plan] {safe_title}", head, base,
                          body=(plan_markdown[:60000] +
                                "\n\n---\nPlan generated by MAICOS. "
                                "Code changes require human review."))


def deployment_status(provider: str, project: str) -> dict[str, Any]:
    from app.devops import providers as devops

    if provider == "vercel":
        return devops.vercel_deployments(project)
    if provider == "railway":
        return devops.railway_status()
    return {"ok": False, "status": "NOT_ENABLED",
            "error": f"unknown provider {provider}"}


def smoke_test(url: str) -> dict[str, Any]:
    """GET the URL; report reachability honestly."""
    try:
        import httpx
        r = httpx.get(url, timeout=15.0, follow_redirects=True)
        ok = r.status_code < 500
        return {"ok": ok, "status": "OK" if ok else "FAILED",
                "http_status": r.status_code, "url": str(r.url)}
    except Exception as exc:
        return {"ok": False, "status": "PROVIDER_ERROR",
                "error": str(exc)[:300]}
