"""Software Company Builder: analyze -> plan-as-PR -> status -> smoke test.

Honest boundaries: repository analysis and deployment STATUS are real when
credentials exist; autonomous production code changes and production
deploys always require approval; full autonomous coding is NOT claimed.
"""
from __future__ import annotations

from typing import Any


def analyze_repo(repo: str) -> dict[str, Any]:
    from app.devops.providers import github_repo_info

    out = github_repo_info(repo)
    if not out.get("ok"):
        return out
    d = out.get("data", {})
    return {"ok": True, "status": "OK",
            "analysis": {
                "repo": d.get("full_name"), "default_branch": d.get("default_branch"),
                "open_issues": d.get("open_issues"),
                "recommendation": ("Standard web stack assumed. Confirm framework "
                                   "before implementation planning.")}}


MAX_GEN_FILES = 10
MAX_FILE_CHARS = 4000


def generate_code(requirements: str, *, stack_hint: str = "") -> dict[str, Any]:
    """LLM generates small file set from requirements (review artifact).

    Never pushes anything. Output is meant for human review + approval
    before any PR. Honest about being a starting point, not tested code.
    """
    requirements = (requirements or "").strip()
    if not requirements:
        return {"ok": False, "status": "FAILED", "error": "requirements required"}
    try:
        from app.llm.gateway import LLMRequest, get_llm
    except Exception as exc:
        return {"ok": False, "status": "NOT_CONFIGURED",
                "error": f"LLM unavailable: {exc}"}
    import json as _json

    sys = ("You generate a SMALL starter codebase as JSON: "
           '{"files":[{"path":"...","content":"..."}]}. '
           f"Max {MAX_GEN_FILES} files, each under {MAX_FILE_CHARS} chars. "
           "Prefer a single-page static site or tiny script unless asked otherwise. "
           "No secrets, no placeholders that pretend to work.")
    try:
        llm = get_llm()
        out = llm.complete(LLMRequest(
            system=sys,
            user=f"Stack: {stack_hint or 'static HTML/CSS/JS'}\n\nRequirements:\n{requirements[:4000]}",
            json_mode=True)).text
        data = _json.loads(out)
        files = [{"path": str(f.get("path", ""))[:200],
                  "content": str(f.get("content", ""))[:MAX_FILE_CHARS]}
                 for f in data.get("files", [])][:MAX_GEN_FILES]
        files = [f for f in files if f["path"] and f["content"]]
        if not files:
            return {"ok": False, "status": "FAILED",
                    "error": "LLM returned no usable files"}
        return {"ok": True, "status": "OK", "files": files,
                "notice": "Untested starter code — review, CI and smoke test required."}
    except Exception as exc:
        return {"ok": False, "status": "PROVIDER_ERROR",
                "error": f"generation failed: {exc}"[:300]}


def build_pr(repo: str, *, requirements: str, branch: str,
             base: str = "main", stack_hint: str = "") -> dict[str, Any]:
    """Generate code + open PR (caller must have approval for the push)."""
    from app.devops.providers import github_create_files_pr

    gen = generate_code(requirements, stack_hint=stack_hint)
    if not gen.get("ok"):
        return gen
    return github_create_files_pr(
        repo, branch, base, gen["files"],
        title=f"MAICOS build: {requirements[:80]}",
        body="Starter implementation. CI + review required before merge.")


def plan_as_pr(repo: str, *, title: str, plan_markdown: str,
               head: str = "", base: str = "main") -> dict[str, Any]:
    """Open a PR containing ONLY the implementation plan document.

    Real code changes ride the normal GitHub review flow afterwards.
    Returns NOT_CONFIGURED without a token; never fakes a merge.
    """
    from app.devops.providers import github_open_pr

    if not head:
        return {"ok": False, "status": "FAILED",
                "error": "head branch required (never push straight to main)"}
    safe_title = (title or "MAICOS implementation plan")[:200]
    return github_open_pr(repo, f"[plan] {safe_title}", head, base,
                          body=(plan_markdown[:60000] +
                                "\n\n---\nPlan generated by MAICOS. "
                                "Code changes require human review."))


def deployment_status(provider: str, project: str) -> dict[str, Any]:
    from app.devops import providers as devops

    if provider == "vercel":
        return devops.vercel_deployments(project)
    if provider == "railway":
        return devops.railway_status()
    return {"ok": False, "status": "NOT_ENABLED",
            "error": f"unknown provider {provider}"}


def smoke_test(url: str) -> dict[str, Any]:
    """GET the URL; report reachability honestly."""
    try:
        import httpx
        r = httpx.get(url, timeout=15.0, follow_redirects=True)
        ok = r.status_code < 500
        return {"ok": ok, "status": "OK" if ok else "FAILED",
                "http_status": r.status_code, "url": str(r.url)}
    except Exception as exc:
        return {"ok": False, "status": "PROVIDER_ERROR",
                "error": str(exc)[:300]}
